### ISSUE TITLE
Support for ng-pattern

### ISSUE THREAD

**Issue by juanpujol** [formly-js/angular-formly-templates-material#10]
Is there a way to bind to ng-pattern on the field definition? Thanks.

**Comment by kamilkisiela** [comment]
@juanpujol At the moment, you can use this http://docs.angular-formly.com/docs/ngmodelattrs

I'm going to add it in next release.

**Comment by kamilkisiela** [comment]
@juanpujol 
https://github.com/formly-js/angular-formly-templates-material/releases/tag/v0.13.0
