### ISSUE TITLE
bug(select): does not collapse on [multiple="false"]

### ISSUE THREAD

**Issue by kamilkisiela** [formly-js/angular-formly-templates-material#22]
[Comment from #4](https://github.com/formly-js/angular-formly-templates-material/issues/4#issuecomment-173940911)

> I think that when multiple is false and that selection occurs, the list should collapse to make selection feel more natural.
> @samcfc

**Comment by kamilkisiela** [comment]
I've made an reproduction of this and yes, it does not work.

http://codepen.io/kamilkisiela/pen/RrQgmX

You can avoid that issue by not setting `templateOptions.multiple`. I will fix it soon.

**Comment by samcfc** [comment]
Thank you very much.

Very impressive quickness.
