### ISSUE TITLE
bug(to.theme): does not work

### ISSUE THREAD

**Issue by kamilkisiela** [formly-js/angular-formly-templates-material#23]
[Comment from #4](https://github.com/formly-js/angular-formly-templates-material/issues/4#issuecomment-173955400)

> Your documentation shows that you can set a theme for each field, but I was not able to get it to work. Is there an example somewhere that I can follow?
> @younessassassi

[Reproduction](http://codepen.io/kamilkisiela/pen/yevXmo)

**Comment by kamilkisiela** [comment]
The manipulator of `theme` uses element with `ngModel` directive to add `md-theme` on it so it's causing a problem.

I will try to fix it asap.

**Comment by kamilkisiela** [comment]
@younessassassi It should be fixed in next release.

**Comment by younessassassi** [comment]
Works great!  thank you
