### ISSUE TITLE
issue with multiple selections on the select field

### ISSUE THREAD

**Issue by younessassassi** [formly-js/angular-formly-templates-material#26]
How to replicate:  Make multiple selections with select options '"multiple": true'. Click on the select field again then deselect all of the selections.  

Result:  Two labels are shown overlapping each other. 

You can use the select demo to replicate the issue here:
http://formly-material.meteor.com/demo/select

**Comment by kamilkisiela** [comment]
Are you sure it's not a angular-material bug?

I will check it soon.

**Comment by kamilkisiela** [comment]
angular/material#7108
