### ISSUE TITLE
Filling available space in row in md-dialog

### ISSUE THREAD

**Issue by jmls** [formly-js/angular-formly-templates-material#27]
I am struggling to get an input field to fill the available space. 

I have 2 "normal" md-inputs, and a formly-form to show the differences

``` html
            <div layout="row">
                <md-input-container flex="">
                    <label>Name</label>
                    <input ng-model="name">
                </md-input-container>
                <md-input-container flex="">
                    <label>Store result in</label>
                    <input ng-model="result">
                </md-input-container>
            </div>
           <formly-form flex="" model="inputData" fields="layout"></formly-form>
```

this gives this result:
![image](https://cloud.githubusercontent.com/assets/929523/13032799/f2466b08-d2f8-11e5-8fa7-58dde7d16714.png)

as you can see, the 2 "normal" inputs fill the available space, whereas the formly form condenses them into a teeny-tiny space

Am I missing some attributes / properties ?

the demo on the website also seems to suggest a similar problem (formly fields condensed)

thanks

**Comment by jmls** [comment]
anyone ? need help ;)

**Comment by kamilkisiela** [comment]
Related to #27
