### ISSUE TITLE
Datepicker template error messages not getting styled

### ISSUE THREAD

**Issue by ejbaker** [formly-js/angular-formly-templates-material#28]
This is, I feel, as much an oversight from the angular material team themselves as it is with your templates, but here goes:

On normal inputs, everything gets wrapped in an md-input-container, including the ng-messages block. Then error classes are bubbled up to md-input-container, which allows for an easy cascade of styling, because the ng-messages block inherits the classes whenever there's an error.

Being incompatible with the md-input-container, the md-datepicker is kind of left out in the cold, and with a default theme applied its error messages don't show proper styling.

JSbin: [here](http://jsbin.com/gisazu/edit?html,css,js,output)

With some fairly trivial CSS, I'm able to style a similarly-situated vanilla datepicker with the sibling attribute selector.

```
md-datepicker.ng-invalid ~ [ng-messages],
md-datepicker.ng-invalid ~ [ng-messages] [ng-messages-exp]{
  font-size: 12px;
  line-height: 14px;
  overflow: hidden;
  transition: all .3s cubic-bezier(.55,0,.55,.2);
  opacity: 1;
  margin-top: 0;
  padding-top: 5px;
}

md-datepicker.ng-invalid ~ [ng-messages],
md-datepicker.ng-invalid ~ [ng-messages] [ng-messages-exp]{
  color: rgb(221,44,0);
}
```

But this fragile solution doesn't work on the formly material datepicker, because of the additional wrapper div in its template. (Which seems to have, perhaps, been intended to receive the ng error classes, but didn't...?)

What I've done as an inadequate patch is just force all ng-messages within the formly-field-datepicker div to always be the 'alert' color... but this is a sad monkey-patch, for a problem that must surely be affecting more than just me. :(

**Comment by kamilkisiela** [comment]
@ejbaker I will check it tomorrow :) For now you can overwrite datepicker field.

**Comment by ejbaker** [comment]
Sadly that's only half the battle. I also need to open a support ticket with Angular Material itself, I think, because all the CSS _really_ expects md-input-container to exist.

```
    md-input-container .md-input:invalid {
      outline: none;
      box-shadow: none; }
md-input-container:not(.md-input-invalid) .md-auto-hide .md-input-message-animation {
    opacity: 0;
    margin-top: -100px; }
 md-input-container .md-input.ng-invalid.ng-dirty {
    padding-bottom: 0;
    border-width: 0 0 2px 0; }
```

(It's difficult to pull out the theme'd CSS, since it's generated in a bunch of style tags. But there's _one_ reference to ng-invalid in conjunction with md-select, and nowhere else.)

But that's not your problem. ;) Thanks for your attention!
