### ISSUE TITLE
Angular Material 1.0.0

### ISSUE THREAD

**Issue by stefanmeschke** [formly-js/angular-formly-templates-material#3]
Hi,

it is possible to update this awesome package to support Angular Material v1.0.0?

**Comment by kamilkisiela** [comment]
Hi @stefanmeschke 

I've just published v0.8.0 with angular-material 1.0.0! Christmas gift from me :)

You need to know that I recently moved most of formly stuff to official [formly](https://atmospherejs.com/formly) organisation on AtmosphereJS and in near future it will be auto updated to the newest versions (thanks to autopublish.meteor.com). 

**wieldo**_:angular-formly-templates-material_ **is no longer maintained**. So I highly recommend you to use official packages so in this case **formly**_:angular-formly-templates-material_

Be aware of breaking changes ([more details](https://github.com/formly-js/angular-formly-templates-material/releases/tag/v0.8.0))

**Comment by stefanmeschke** [comment]
Thank you!
Happy holidays and and a healthy and successful new year!
