### ISSUE TITLE
Datepicker - no placeholder

### ISSUE THREAD

**Issue by gvdonovan-axio** [formly-js/angular-formly-templates-material#30]
While there is a label on the datepicker it doesn't float like the input field types.  The label should likely be the placeholder by default and then float as input fields do when there is a value.

**Comment by kamilkisiela** [comment]
This is how [angular-material](https://material.angularjs.org/latest/demo/datepicker) works.

[Docs for `datepicker`](https://github.com/formly-js/angular-formly-templates-material/blob/master/docs/types/datepicker.md)
