### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by mikamusz** [formly-js/angular-formly-templates-material#31]
Hi guys,

First of all I'm new in formly material. Do you have any idea how I can build the multi select drop down? Currently I think it is not supported yet and I've tried modify using the formlyConfig but not able to do it. Could you please advise?

**Comment by kamilkisiela** [comment]
@mikamusz You can use `select` with [multiple](https://github.com/formly-js/angular-formly-templates-material/blob/master/docs/types/select.md#templateoptionsmultiple--boolean) option
