### ISSUE TITLE
assumption of existence of templateOptions

### ISSUE THREAD

**Issue by jmls** [formly-js/angular-formly-templates-material#32]
there are several places where the code assumes that field.templateOptions is defined. This may not be the case (or it may be that some code adding templateOptions if is undefined is missing)

this obviously causes problems

A couple of examples of this are:

`function ngModelAttrsTransformer : if (typeof field.templateOptions[name] !== 'undefined')`

`return field.type === 'input' && field.templateOptions.type === 'number';`

etc

**Comment by kamilkisiela** [comment]
@jmls You can work on PR if you want.

I will fix it by the end of the week.

**Comment by kamilkisiela** [comment]
It will be fixed in the next release
