### ISSUE TITLE
Support for higher versions of angular

### ISSUE THREAD

**Issue by tilwinjoy** [formly-js/angular-formly-templates-material#34]
Hi, Why is there a hard dependency on angular `~1.4.0`, and others..? Does this break with higher versions..? Is it possible to support higher versions like `1.5.x`..?

**Comment by B45man** [comment]
I am using Angular 1.5.3 and am not having any problems using this plugin. If you haven't already, just try to use this, you might get lucky.

**Comment by tilwinjoy** [comment]
@B45man  There won't be any issues, but the problem is when we use heigher versions of dependencies bower won't be able to resolve the dependencies automatically and will prompt for manual input. That's not a good thing when we handover a package to non technical people like, testers for example

**Comment by kamilkisiela** [comment]
@tilwinjoy It will be changed in the next release (this weekend).

**Comment by lwalter** [comment]
@kamilkisiela Hey there, just curious if this will be resolved in the near future? We have a dependency on angular 1.5.5 and would like to avoid manual version resolution when running bower installs.

**Comment by kamilkisiela** [comment]
I published `0.14.2`, should be okay now :)

**Comment by tilwinjoy** [comment]
@kamilkisiela  Hi, `bower.json` is untouched in the latest release and still has hard dependency on older angular version.

**Comment by tilwinjoy** [comment]
Hi, this is still unresolved... Should I make a PR?

**Comment by jpattersonz** [comment]
It appears you only added support for angular 1.5.x in the package.json file.  It's also needed in the bower.json file.

**Comment by EdineraWeb** [comment]
Can we have this bower.json file changed, please, or should we make pull request?
