### ISSUE TITLE
"npm run build" throws error.

### ISSUE THREAD

**Issue by creimers** [formly-js/angular-formly-templates-material#40]
Because I want to add autocomplete to `md-chips`, I forked your repo.

However, if I run `npm run build` I get the following error (from `build:prod`):

```
ERROR in dist/formly-material.min.js from UglifyJs
Unexpected token: name (angular) [./src/index.js:1,0]
```

Any idea about what is going wrong?

**Comment by kamilkisiela** [comment]
I just run `npm run build` to release new version and it's working fine. But let me check it again.

Try to `npm update` packages, maybe this will fix it.

**Comment by creimers** [comment]
Sorry, something seems to have been misconfigured on my machine. It works indeed.

**Comment by kamilkisiela** [comment]
Great :) Can't wait for pull request :smile:
