### ISSUE TITLE
Respect fomlyConfig.errorExistsAndShouldBeVisibleExpression

### ISSUE THREAD

**Issue by seangwright** [formly-js/angular-formly-templates-material#7]
Here is my global app config function where I specify under what conditions validation should appear

```
function config($locationProvider, formlyConfigProvider) {
        $locationProvider.html5Mode(true).hashPrefix('!');

        formlyConfigProvider.extras.errorExistsAndShouldBeVisibleExpression = function($viewValue, $modelValue, scope) {
            return (scope.fc.$touched && scope.form.$submitted);
        };
    }
```

When using `ng-messages` directly I can set the display expression as
`<ng-messages for="form.$submitted && form.myField.$error">` or `<ng-messages for="searchForm.$submitted && searchForm.myField.$touched">`.

Should `formlyConfigProvider.extras.errorExistsAndShouldBeVisibleExpression` give me a way to interact with that `for` attribute on ng-messages?

Or in the case of the messages wrapper for these templates I want to be able to modify `ng-messages="fc.$error"` with `errorExistsAndShouldBeVisibleExpression`

**Comment by kamilkisiela** [comment]
@sgwatgit 
Look at this: https://github.com/formly-js/angular-formly-templates-material/commit/7d3c9b9ace04987938ddbe26268a4bcea4ac6d41

It's a shortcut for `options.validation.errorExistsAndShouldBeVisible` ([see docs](http://docs.angular-formly.com/docs/field-configuration-object#section-validation-errorexistsandshouldbevisible))

It returns boolean value basing on this rule `field invalid && (field touched || validation.show)`.
So if you want to force showing validation messages on some field you can set `validation.show: true`.

## 

About `errorExistsAndShouldBeVisibleExpression`. You can use it now.

## 

If you're able to test it, I would be grateful. Please let me know if it works and this is what you wanted to achieve.

edit: I pushed new [dist files](https://github.com/formly-js/angular-formly-templates-material/commit/5fc2e7d2babf14a61b714d15c6110f1de83b221c) so you can use them now.

**Comment by seangwright** [comment]
@kamilkisiela This looks like it is working correctly now. I am able to globally set the conditions for showing error messages through `formlyConfigProvider.extras.errorExistsAndShouldBeVisibleExpression`

Thanks!`
