### ISSUE TITLE
Tabbing past a required select element does not persist error message

### ISSUE THREAD

**Issue by seangwright** [formly-js/angular-formly-templates-material#8]
When I set a `select` field as `required: true` I have noticed that the validation error message appears and then quickly disappears when I tab into and then tab out of the `select` element without making a selection.

Here is an example field definition

```
{
    key: 'genres',
    type: 'select',
    templateOptions: {
        label: 'Genre',
        options: [{name: 'sci-fi'}, {name: 'mystery'}],
        labelProp: "name",
        valueProp: "name",
        required: true
    }
}
```

Here is a live example of this bug http://jsbin.com/yuvuwo/6/edit?html,js,output

Put your cursor in the first text field and then tab through each element until you reach the Submit button. You will notice that the message `This field is required` appears below the `select` field as you tab out of it but then it disappears again.

**Note**: If you tab through the fields a second time, the error is persisted when tabbing out of the `select` element.

**Comment by kamilkisiela** [comment]
I think it is a angular-material bug.

Focus in: field's $untouched === true
Focus out: field's $untouched === false

but then: field's $untouched === true

Look at this: http://codepen.io/kamilkisiela/pen/QyGJeG

**Comment by seangwright** [comment]
Yeah, looks like the issue might be here https://github.com/angular/material/blob/v1.0.1/src/components/select/select.js

``` javascript
// Wait until postDigest so that we attach after ngModel's 
// blur listener so we can set untouched.
$mdUtil.nextTick(function () {
  element.on('blur', function() {
    if (untouched) {
      untouched = false;
      ngModelCtrl.$setUntouched();
    }

    if (selectScope.isOpen) return;
    containerCtrl && containerCtrl.setFocused(false);
    inputCheckValue();
  });
});
```

Not sure why they set `untouched = false` but then set the model `$untouched` to true.

I'll close this and watch the issue on the angular material repo.

Thanks!

**Comment by kamilkisiela** [comment]
@sgwatgit $mdUtil.nextTick is like $timeout with 0 ms so I think it's because of that.
